name: Build WorkFlow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "amigoscode"
      - name: JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Maven Clean Verify
        run: mvn -B -ntp clean verify 
