name: My First WorkFlow
on:
  push:
    branches:
      - main
      
jobs:
  myFirstJob:
    runs-on: ubuntu-latest
    steps:
    - name: My First Step
      run: printenv
    - name: My Second Step
      run: |
            echo "Amigoscode"
            echo "Hello" > file.txt
            ls
    - name: My Third Step
      run: sleep 20
      
    - name: My First Action
      uses: actions/checkout@v6
    
    - name: ls repository
      run: |
        ls 
      
