name: Deploy WorkFlow
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'Temurin'
          java-version: '21'
      - name: Generate Build Number
        run: |
          BUILD_NUMBER=$(date +'%d%m%Y%H%M%S')
      - name: echo $BUILD_NUMBER
        run: echo $BUILD_NUMBER
